### ISSUE TITLE
Support for vpn.ht

### ISSUE THREAD

**Issue by tmiland** [dustingrady/CoalMine#1]
Hello, found this on Reddit. :+1: 

Added support for vpn.ht 

`        print('To run: "python canary.py -<flag>\nValid flags:\n-nord\n-vpnsecure\n-slickvpn\n-ivpn\n-proxy.sh\n-proton\n-spyoff\n-azire\n-liquid\n-ace\n-cloudflare\n-vpnht')`

`[VPNHT]
link = https://vpn.ht/canary.txt
canary = To this date there have been no warrants, searches or seizures that have not been reported in our Transparency Report, and that have actually taken place. The sky is blue :)
         No warrants, searches or seizures of any kind have ever been performed on VPN.ht assets.`

Noticed it failed if i used (dot) in the name, so i just removed it. 

Thanks!

**Comment by dustingrady** [comment]
Nice, thank you. Feel free to open a pull request and I'll merge back into master.
